# Generated by Django 3.1.2 on 2020-11-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(default='', max_length=50),
        ),
    ]
