# Generated by Django 3.1.2 on 2020-11-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20201130_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(default='', max_length=50),
        ),
    ]
