# Generated by Django 3.1.2 on 2020-11-30 12:26

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20201130_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=mdeditor.fields.MDTextField(default=mdeditor.fields.MDTextField(null=True), max_length=50),
        ),
    ]
