# Generated by Django 3.1.2 on 2020-12-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AddField(
            model_name='article',
            name='topping',
            field=models.BooleanField(default=False),
        ),
    ]
