# Generated by Django 3.1.2 on 2020-12-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20201223_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-topping', 'views')},
        ),
    ]
