# Generated by Django 3.1.2 on 2020-12-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20201223_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-topping', '-views')},
        ),
    ]
