# Generated by Django 3.1.2 on 2020-12-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20201224_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='topping',
            new_name='pin',
        ),
    ]
